version: "3"
services:
  server:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://user:pass@postgres:5432/db
      - DEBUG=1
      - KEY=Gj7eXAMLBlq6FMS6ganX0OMVX2AweeWvWdlKh0yFErU=
      - SECRET=Wu6bt7LssNi8W7S$J4imJaVB!t)QmHhyi4!Na4Y^
    ports:
      - "5000:5000"
    command: ["python", "app.py"]
    restart: on-failure
    volumes:
      - "./:/home/app"
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - "8081:5432"