"""empty message

Revision ID: 54f353faaa2e
Revises: 
Create Date: 2020-07-06 22:25:38.485261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f353faaa2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friends',
    sa.Column('user_id_1', sa.Integer(), nullable=True),
    sa.Column('user_id_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_2'], ['users.id'], )
    )
    op.create_table('pending_friends',
    sa.Column('user_id_1', sa.Integer(), nullable=True),
    sa.Column('user_id_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_2'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_friends')
    op.drop_table('friends')
    op.drop_table('users')
    # ### end Alembic commands ###
